//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartKithen.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        public int Id { get; set; }
        public int RecipeId { get; set; }
        public int ProductId { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Recipes Recipes { get; set; }
    }
}
