//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartKithen.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredients()
        {
            this.StepIngredients = new HashSet<StepIngredients>();
        }
    
        public int Id { get; set; }
        public int RecipeId { get; set; }
        public int ProductId { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Recipes Recipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StepIngredients> StepIngredients { get; set; }
    }
}
