//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartKithen.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepIngredients
    {
        public int Id { get; set; }
        public int StepId { get; set; }
        public int IngredientId { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual RecipeSteps RecipeSteps { get; set; }
    }
}
